In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib

In [3]:
df1 = pd.read_csv('heart_2020_cleaned.csv')

In [4]:
df1.shape

(319795, 18)

In [5]:
df1.head()

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0           No  16.60     Yes              No     No             3.0   
1           No  20.34      No              No    Yes             0.0   
2           No  26.58     Yes              No     No            20.0   
3           No  24.21      No              No     No             0.0   
4           No  23.71      No              No     No            28.0   

   MentalHealth DiffWalking     Sex  AgeCategory   Race Diabetic  \
0          30.0          No  Female        55-59  White      Yes   
1           0.0          No  Female  80 or older  White       No   
2          30.0          No    Male        65-69  White      Yes   
3           0.0          No  Female        75-79  White       No   
4           0.0         Yes  Female        40-44  White       No   

  PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0              Yes  Very good        5.0    Yes            No        Yes  
1              Yes  Very good        7.0     No            No         No  
2              Yes       Fair        8.0    Yes            No         No  
3               No       Good        6.0     No            No        Yes  
4              Yes  Very good        8.0     No            No         No

In [6]:
df1.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [7]:
df2 = df1.drop(['DiffWalking','SleepTime','MentalHealth','GenHealth'],axis=1)
df2.nunique()

HeartDisease           2
BMI                 3604
Smoking                2
AlcoholDrinking        2
Stroke                 2
PhysicalHealth        31
Sex                    2
AgeCategory           13
Race                   6
Diabetic               4
PhysicalActivity       2
Asthma                 2
KidneyDisease          2
SkinCancer             2
dtype: int64

In [8]:
df2["Race"].unique()

array(['White', 'Black', 'Asian', 'American Indian/Alaskan Native',
       'Other', 'Hispanic'], dtype=object)

In [202]:
df2['Diabetic'].unique()

array(['Yes', 'No'], dtype=object)

In [65]:
df2['HeartDisease'].value_counts()

No     283979
Yes     26476
Name: HeartDisease, dtype: int64

In [11]:
!pip install imbalanced-learn

In [12]:
!pip3 install imblearn

In [13]:
dummies= pd.get_dummies(df2.Race)
dummies.head()

American Indian/Alaskan Native  Asian  Black  Hispanic  Other  White
0                               0      0      0         0      0      1
1                               0      0      0         0      0      1
2                               0      0      0         0      0      1
3                               0      0      0         0      0      1
4                               0      0      0         0      0      1

In [14]:
import imblearn

In [15]:
dummies2= pd.get_dummies(df2.AgeCategory)
dummies2.head()

18-24  25-29  30-34  35-39  40-44  45-49  50-54  55-59  60-64  65-69  \
0      0      0      0      0      0      0      0      1      0      0   
1      0      0      0      0      0      0      0      0      0      0   
2      0      0      0      0      0      0      0      0      0      1   
3      0      0      0      0      0      0      0      0      0      0   
4      0      0      0      0      1      0      0      0      0      0   

   70-74  75-79  80 or older  
0      0      0            0  
1      0      0            1  
2      0      0            0  
3      0      1            0  
4      0      0            0

In [16]:
df3 = pd.DataFrame()

In [17]:
df2 =df2.mask(df2['Diabetic'] == 'No, borderline diabetes')
df2 =df2.mask(df2['Diabetic'] == 'Yes (during pregnancy)')
df2.dropna(inplace=True)
df2['Diabetic'].unique()

array(['Yes', 'No'], dtype=object)

In [18]:
df3[['hd']] = np.where(df2[['HeartDisease']]=='Yes',1,0)
df3[['physical_health']] = df2[['PhysicalHealth']]
df3[['bmi']] =df2[['BMI']]
df3[['is_smoker']] = np.where(df2[['Smoking']]=='Yes',1,0)
df3[['is_drinker']] = np.where(df2[['AlcoholDrinking']]=='Yes',1,0)
df3[['had_stroke']] = np.where(df2[['Stroke']]=='Yes',1,0)
df3[['gender']] = np.where(df2[['Sex']]=='Male',1,0)
df3[['exercise']] = np.where(df2[['PhysicalActivity']]=='Yes',1,0)
df3[['has_asthma']] = np.where(df2[['Asthma']]=='Yes',1,0)
df3[['has_db']] = np.where(df2[['Diabetic']]=='Yes',1,0)
df3[['has_kd']] = np.where(df2[['KidneyDisease']]=='Yes',1,0)
df3[['has_sc']] = np.where(df2[['SkinCancer']]=='Yes',1,0)

In [19]:
df3.head(10)

hd  physical_health    bmi  is_smoker  is_drinker  had_stroke  gender  \
0   0              3.0  16.60          1           0           0       0   
1   0              0.0  20.34          0           0           1       0   
2   0             20.0  26.58          1           0           0       1   
3   0              0.0  24.21          0           0           0       0   
4   0             28.0  23.71          0           0           0       0   
5   1              6.0  28.87          1           0           0       0   
6   0             15.0  21.63          0           0           0       0   
7   0              5.0  31.64          1           0           0       0   
8   0              NaN    NaN          0           0           0       1   
9   1              0.0  40.69          1           0           0       1   

   exercise  has_asthma  has_db  has_kd  has_sc  
0         1           1       1       0       1  
1         1           0       0       0       0  
2         1           1       1       0       0  
3         0           0       0       0       1  
4         1           0       0       0       0  
5         0           0       0       0       0  
6         1           1       0       0       1  
7         0           1       1       0       0  
8         1           0       0       0       0  
9         0           1       1       0       0

In [20]:
df3['bmi'].max()

94.85

In [21]:
df3 = pd.concat([df3,dummies], axis=1)
df3 = pd.concat([df3,dummies2], axis = 1)

In [22]:
df3.dropna(inplace=True)

In [23]:
df3.shape


(301524, 31)

In [24]:
df3.head()

hd  physical_health    bmi  is_smoker  is_drinker  had_stroke  gender  \
0  0.0              3.0  16.60        1.0         0.0         0.0     0.0   
1  0.0              0.0  20.34        0.0         0.0         1.0     0.0   
2  0.0             20.0  26.58        1.0         0.0         0.0     1.0   
3  0.0              0.0  24.21        0.0         0.0         0.0     0.0   
4  0.0             28.0  23.71        0.0         0.0         0.0     0.0   

   exercise  has_asthma  has_db  ...  35-39  40-44  45-49  50-54  55-59  \
0       1.0         1.0     1.0  ...      0      0      0      0      1   
1       1.0         0.0     0.0  ...      0      0      0      0      0   
2       1.0         1.0     1.0  ...      0      0      0      0      0   
3       0.0         0.0     0.0  ...      0      0      0      0      0   
4       1.0         0.0     0.0  ...      0      1      0      0      0   

   60-64  65-69  70-74  75-79  80 or older  
0      0      0      0      0            0  
1      0      0      0      0            1  
2      0      1      0      0            0  
3      0      0      0      1            0  
4      0      0      0      0            0  

[5 rows x 31 columns]

In [25]:
X = df3.drop('hd',axis=1)

In [26]:
X.head()

physical_health    bmi  is_smoker  is_drinker  had_stroke  gender  \
0              3.0  16.60        1.0         0.0         0.0     0.0   
1              0.0  20.34        0.0         0.0         1.0     0.0   
2             20.0  26.58        1.0         0.0         0.0     1.0   
3              0.0  24.21        0.0         0.0         0.0     0.0   
4             28.0  23.71        0.0         0.0         0.0     0.0   

   exercise  has_asthma  has_db  has_kd  ...  35-39  40-44  45-49  50-54  \
0       1.0         1.0     1.0     0.0  ...      0      0      0      0   
1       1.0         0.0     0.0     0.0  ...      0      0      0      0   
2       1.0         1.0     1.0     0.0  ...      0      0      0      0   
3       0.0         0.0     0.0     0.0  ...      0      0      0      0   
4       1.0         0.0     0.0     0.0  ...      0      1      0      0   

   55-59  60-64  65-69  70-74  75-79  80 or older  
0      1      0      0      0      0            0  
1      0      0      0      0      0            1  
2      0      0      1      0      0            0  
3      0      0      0      0      1            0  
4      0      0      0      0      0            0  

[5 rows x 30 columns]

In [27]:
y = df3.hd

In [28]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: hd, dtype: float64

In [283]:
len(X.columns)

30

In [284]:
from imblearn.over_sampling import SMOTE, SMOTENC
os = SMOTENC(categorical_features=[18,19],sampling_strategy='auto', random_state=42)

In [285]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=10, stratify=y)

In [286]:
columns = X_train.columns
os_data_X,os_data_y=os.fit_resample(X_train, y_train)
os_data_X = pd.DataFrame(data=os_data_X,columns=columns )
os_data_y= pd.DataFrame(data=os_data_y,columns=['hd'])

In [287]:
os_data_y.value_counts()

hd 
0.0    193062
1.0    193062
dtype: int64

In [288]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(os_data_X,os_data_y)
lr_clf.score(X_test,y_test)

-1.0171449998675919

In [289]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

In [290]:
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
cross_val_score(LinearRegression(),os_data_X,os_data_y,cv=cv)

array([0.30467119, 0.30325879, 0.30191664, 0.30074408, 0.30187688])

In [291]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [258]:
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                'normalize': [True, False]
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [0,1,2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion' : ['mse','friedman_mse'],
                'splitter': ['best','random']
            }
        },
        'random_forest' : {
            'model' : RandomForestClassifier(),
            'params' : {
                'n_estimators': [100],
            }
        },
        'logistic_regression' :{
            'model' : LogisticRegression(),
            'params' : {

            }
        }
    }
    scores = []
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False, n_jobs=-1)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(os_data_X,os_data_y)

C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(
C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\model_selection\_search.py:910: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  self.best_estimator_.fit(X, y, **fit_params)
C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\linear_mo

model  best_score                                 best_params
0    linear_regression    0.275664                         {'normalize': True}
1                lasso    0.275664         {'alpha': 0, 'selection': 'random'}
2        decision_tree    0.525333  {'criterion': 'mse', 'splitter': 'random'}
3        random_forest    0.892338                       {'n_estimators': 100}
4  logistic_regression    0.732561                                          {}

In [292]:
from sklearn.model_selection import KFold
cv = ShuffleSplit(n_splits=10, test_size=0.3, random_state=0)
rf_clf = GridSearchCV(RandomForestClassifier(),{
    'n_estimators':[100],'n_jobs':[-1]}, cv=cv, return_train_score=False )
rf_clf.fit(os_data_X.values,os_data_y.values.ravel())


GridSearchCV(cv=ShuffleSplit(n_splits=10, random_state=0, test_size=0.3, train_size=None),
             estimator=RandomForestClassifier(),
             param_grid={'n_estimators': [100], 'n_jobs': [-1]})

In [293]:
df0 = pd.DataFrame(rf_clf.cv_results_)
df0[['param_n_estimators','mean_test_score']]

param_n_estimators  mean_test_score
0                100         0.892328

In [294]:
y_pred =rf_clf.predict(X_test)


C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [295]:
rf_clf.best_estimator_.feature_importances_

array([0.04488751, 0.3432415 , 0.07642038, 0.02470756, 0.05281548,
       0.06410482, 0.05402439, 0.03634016, 0.08517384, 0.03277139,
       0.04117535, 0.00308888, 0.00391332, 0.00711   , 0.00674584,
       0.00435156, 0.01026666, 0.0068198 , 0.00652947, 0.00714508,
       0.00862858, 0.00769237, 0.00859406, 0.00827335, 0.00790133,
       0.01029077, 0.01011536, 0.00896754, 0.00853343, 0.00937023])

In [298]:
from sklearn.metrics import confusion_matrix, plot_confusion_matrix
cm = confusion_matrix(y_test, y_pred, )
cm

array([[75912,  6830],
       [ 6291,  1425]], dtype=int64)

In [299]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.92      0.92      0.92     82742
         1.0       0.17      0.18      0.18      7716

    accuracy                           0.85     90458
   macro avg       0.55      0.55      0.55     90458
weighted avg       0.86      0.85      0.86     90458



In [183]:
def optimize_rf(X,y):
    algos= {
        'random_forest' : {
            'model' : RandomForestClassifier(),
            'params' : {
                'n_estimators': [200],
                'n_jobs' : [-1],
                'max_depth' : [8,16,32,64],
                'criterion' : ['gini','log_loss'],
                'max_features' : ['sqrt','log2'],

            }
        }
    }
    scores = []
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])


In [184]:
optimize_rf(os_data_X,os_data_y)

C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\shane\anaconda3\envs\myenv\lib\site-packages\sklearn\model_selection\_validation.py:686:

model  best_score  \
0  random_forest    0.893457   

                                         best_params  
0  {'criterion': 'gini', 'max_depth': 64, 'max_fe...

In [189]:
rf1 =RandomForestClassifier(max_features='sqrt',n_estimators=200,n_jobs=-1, max_depth=64)
rf1.fit(os_data_X,os_data_y)

C:\Users\shane\AppData\Local\Temp/ipykernel_4432/3980558263.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf1.fit(os_data_X,os_data_y)


RandomForestClassifier(max_depth=64, n_estimators=200, n_jobs=-1)

In [190]:
y_pred =rf1.predict(X_test)

In [196]:
rf1.feature_importances_

array([0.04454533, 0.33693789, 0.08290198, 0.02763083, 0.05278481,
       0.06828807, 0.05564222, 0.03870575, 0.08920077, 0.03252033,
       0.04335081, 0.00419695, 0.00466622, 0.00759397, 0.00643339,
       0.00539649, 0.01198775, 0.00599175, 0.0059178 , 0.0062433 ,
       0.00615447, 0.0062336 , 0.00669063, 0.00687132, 0.00701952,
       0.0075819 , 0.00788649, 0.0075095 , 0.00636067, 0.00675549])

In [197]:
cm = confusion_matrix(y_test, y_pred, )
cm

array([[75772,  7013],
       [ 6235,  1438]], dtype=int64)

In [131]:
def predict_heart_disease(race,age_group, bmi,physical_health,gender, drinker, had_stroke, exercise, has_kd, has_db, has_sc, has_asthma):
    loc_index_race = np.where(X.columns == race)[0][0]
    loc_index_age = np.where(X.columns == age_group)[0][0]
    loc_index_ph = np.where(X.columns == age_group)[0][0]
    # convert_yes(gender, drinker, had_stroke, exercise, has_kd, has_db, has_sc, has_asthma)
    features=[gender, drinker, had_stroke, exercise, has_kd, has_db, has_sc, has_asthma]
    for f in range(len(features)):
        if features[f] == 'Yes':
            features[f] = 1
        else:
            features[f] = 0

    print(features)
    x= np.zeros(len(X.columns))
    x[0] = features[0]
    x[1] = features[1]
    x[2] = features[2]
    x[3] = features[3]
    x[4] = features[4]
    x[5] = features[5]
    x[6] = features[6]
    x[7] = features[7]
    if loc_index_race>=0:
        x[loc_index_race] = 1
    if loc_index_age>=0:
        x[loc_index_age] = 1
    if loc_index_ph>=0:
        x[loc_index_race] = 1
    print(loc_index_race)
    return rf_clf.predict([x])[0]


In [132]:
predict_heart_disease('White','55-59',80,30,'Yes','Yes','No','Yes','No','Yes','Yes','No')

[1, 1, 0, 1, 0, 1, 1, 0]
16


0.0

In [133]:
predict_heart_disease('White','55-59',80,30,'Yes','Yes','Yes','Yes','Yes','Yes','Yes','No')

[1, 1, 1, 1, 1, 1, 1, 0]
16


1.0

In [149]:
predict_heart_disease('White','60-64',60,10,'No','Yes','No','Yes','No','Yes','Yes','No')

[0, 1, 0, 1, 0, 1, 1, 0]
16


0.0

In [150]:
predict_heart_disease('Black','55-59',80,30,'No','Yes','No','Yes','No','Yes','Yes','Yes')

[0, 1, 0, 1, 0, 1, 1, 1]
13


0.0

In [151]:
predict_heart_disease('Asian','55-59',60,20,'Yes','Yes','Yes','Yes','No','Yes','Yes','No')

[1, 1, 1, 1, 0, 1, 1, 0]
12


0.0

In [148]:
predict_heart_disease('Hispanic','55-59',80,0,'No','Yes','No','Yes','No','Yes','Yes','No')

[0, 1, 0, 1, 0, 1, 1, 0]
14


0.0

In [77]:
loc_index = np.where(X.columns == 'Asian')[0][0]
loc_index

12

In [ ]:
import seaborn as sn
sn.heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')

In [ ]:
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
confusion_matrix(y_true, y_pred)